package com.phm.hec.PD.FacilityPageObjects;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

public class AddFacilityPageObjects {
	public WebElement TxtFacilityName;
	@FindBy(id = "ContentPlaceHolder1_ddlFacilityType")
	public WebElement DdlFacilityType;
	@FindBy(id = "ContentPlaceHolder1_CheckFacility")
	public WebElement ChkFacilityType;
	@FindBy(id = "ContentPlaceHolder1_btnAssignAccount")
	public WebElement BtnAssignAccount;
	@FindBy(id = "ContentPlaceHolder1_txtFacilityAddress1")
	public WebElement TxtFacilityAddress1;
	@FindBy(id = "ContentPlaceHolder1_txtFacilityAddress2")
	public WebElement TxtFacilityAddress2;
	@FindBy(id = "ContentPlaceHolder1_txtFacilityCity")
	public WebElement TxtFacilityCity;
	@FindBy(id = "ContentPlaceHolder1_ddlFacilityState")
	public WebElement DdlFacilityState;
	@FindBy(id = "ContentPlaceHolder1_txtFacilityZip")
	public WebElement DdlFacilityZip;
	@FindBy(id = "ContentPlaceHolder1_ddlFacilityCounty")
	public WebElement DdlFacilityCounty;
	@FindBy(id = "ContentPlaceHolder1_txtFacilityPhone")
	public WebElement TxtFacilityPhone;
	@FindBy(id = "ContentPlaceHolder1_txtFacilityFax")
	public WebElement TxtFacilityFax;
	@FindBy(id = "ContentPlaceHolder1_txtGroupNPI")
	public WebElement TxtGroupNPI;
	@FindBy(id = "ContentPlaceHolder1_txtTaxID")
	public WebElement TxtTaxID;
	@FindBy(id = "ContentPlaceHolder1_txtTermDate")
	public WebElement TxtTermDate;
	@FindBy(id = "ContentPlaceHolder1_imgTermDate")
	public WebElement TxtImgTermDate;
	@FindBy(id = "ContentPlaceHolder1_ddlStatus")
	public WebElement DdlStatus;
	@FindBy(id = "ContentPlaceHolder1_ddlEHRorPaper")
	public WebElement DdlEhrorPaper;
	@FindBy(id = "ContentPlaceHolder1_txtEHRName")
	public WebElement TxtEhrName;
	@FindBy(id = "ContentPlaceHolder1_txtEHRLiveDate")
	public WebElement TxtEhrLiveDate;
	@FindBy(id = "ContentPlaceHolder1_imgEHRLiveDate")
	public WebElement TxtImgEhrLiveDate;
	@FindBy(id = "ContentPlaceHolder1_txtEHRVersion")
	public WebElement TxtEhrVersion;
	@FindBy(id = "ContentPlaceHolder1_txtEHRContactFirstName")
	public WebElement TxtEhrContactFirstName;
	@FindBy(id = "ContentPlaceHolder1_txtEHRContactMiddleInt")
	public WebElement TxtEhrContactMiddleInt;
	@FindBy(id = "ContentPlaceHolder1_txtEHRContactLastName")
	public WebElement TxtEhrContactLastName;
	@FindBy(id = "ContentPlaceHolder1_txtEHRContactAddress1")
	public WebElement TxtEhrContactAddress1;
	@FindBy(id = "ContentPlaceHolder1_txtEHRContactAddress2")
	public WebElement TxtEhrContactAddress2;
	@FindBy(id = "ContentPlaceHolder1_txtEHRContactCity")
	public WebElement TxtEhrContactCity;
	@FindBy(id = "ContentPlaceHolder1_ddlEHRContactState")
	public WebElement DdlEhrContactState;
	@FindBy(id = "ContentPlaceHolder1_txtEHRContactZip")
	public WebElement TxtEhrContactZip;
	@FindBy(id = "ContentPlaceHolder1_txtEHRContactPhone")
	public WebElement TxtEhrContactPhone;
	@FindBy(id = "ContentPlaceHolder1_txtEHRContactEmail")
	public WebElement TxtEhrContactEmail;
	@FindBy(id = "ContentPlaceHolder1_txtBillingCmpName")
	public WebElement TxtBillingCmpName;
	@FindBy(id = "ContentPlaceHolder1_txtBillingSys")
	public WebElement TxtBillingSys;
	@FindBy(id = "ContentPlaceHolder1_txtBillingLvDate")
	public WebElement TxtBillingLvDate;
	@FindBy(id = "ContentPlaceHolder1_imgBillLiveDate")
	public WebElement TxtImgBillingLiveDate;
	@FindBy(id = "ContentPlaceHolder1_txtBillFirstName")
	public WebElement TxtBillFirstName;
	@FindBy(id = "ContentPlaceHolder1_txtBillMiddleInit")
	public WebElement TxtBillMiddleInit;
	@FindBy(id = "ContentPlaceHolder1_txtBillLastName")
	public WebElement TxtBillLastName;
	@FindBy(id = "ContentPlaceHolder1_txtBillAddress1")
	public WebElement TxtBillAddress1;
	@FindBy(id = "ContentPlaceHolder1_txtBillAddress2")
	public WebElement TxtBillAddress2;
	@FindBy(id = "ContentPlaceHolder1_txtBillCity")
	public WebElement TxtBillCity;
	@FindBy(id = "ContentPlaceHolder1_ddlBillState")
	public WebElement DdlBillState;
	@FindBy(id = "ContentPlaceHolder1_txtBillZip")
	public WebElement TxtBillZip;
	@FindBy(id = "ContentPlaceHolder1_txtBillPhone")
	public WebElement TxtBillPhone;
	@FindBy(id = "ContentPlaceHolder1_txtBillEmail")
	public WebElement TxtBillEmail;
	@FindBy(id = "ContentPlaceHolder1_txtVARPhone")
	public WebElement TxtVARPhone;
	@FindBy(id = "ContentPlaceHolder1_ddlASPClientServer")
	public WebElement DdlAspClientServer;
	@FindBy(id = "ContentPlaceHolder1_txtBillingSystem")
	public WebElement TxtBillingSystem;
	@FindBy(id = "ContentPlaceHolder1_txtVAR")
	public WebElement TxtVar;
	@FindBy(id = "ContentPlaceHolder1_btnAddContact")
	public WebElement BtnAddContact;
	@FindBy(id = "ContentPlaceHolder1_btnAddCallLog")
	public WebElement BtnAddCallLog;
	@FindBy(id = "ContentPlaceHolder1_btnSaveFacility")
	public WebElement BtnSaveFacility;
	@FindBy(id = "ContentPlaceHolder1_btnClearFacility")
	public WebElement BtnClearFacility;
	@FindBy(id = "ContentPlaceHolder1_btnBackFacility")
	public WebElement BtnBackFacility;

}
